import "math.ms";

// class Animal {
//   init(name) {
//     this.name = name;
//   }
//
//   speak() {
//     print "Animal " + this.name + " make a sound.";
//   }
// }
//
// class Dog : Animal {
//   init(name) {
//     super.init(name);
//   }
//
//   speak() {
//     print "Dog " + this.name + " barks";
//   }
// }
//
//
// var animal = Animal("Generic");
// animal.speak();
//
// var dog = Dog("Tommy")
// dog.speak();

print math.add(1, 2);
