#ifndef MSLANGC_RUNTIME_OPCODE_H_
#define MSLANGC_RUNTIME_OPCODE_H_

typedef enum MsOpcode {
  MS_OP_CONSTANT,
  MS_OP_NIL,
  MS_OP_TRUE,
  MS_OP_FALSE,
  MS_OP_POP,
  MS_OP_GET_LOCAL,
  MS_OP_SET_LOCAL,
  MS_OP_GET_GLOBAL,
  MS_OP_DEFINE_GLOBAL,
  MS_OP_SET_GLOBAL,
  MS_OP_EQUAL,
  MS_OP_GREATER,
  MS_OP_LESS,
  MS_OP_ADD,
  MS_OP_SUBTRACT,
  MS_OP_MULTIPLY,
  MS_OP_DIVIDE,
  MS_OP_NOT,
  MS_OP_NEGATE,
  MS_OP_PRINT,
  MS_OP_JUMP,
  MS_OP_JUMP_IF_FALSE,
  MS_OP_LOOP,
  MS_OP_RETURN
} MsOpcode;

#endif
